/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: AGPL-3.0-only
 */
namespace Corsinvest.AppHero.Core.UI;

public enum UIIcon
{
    None,
    Settings,
    Widget,
    Link,
    Create,
    Delete,
    Edit,
    Save,
    Search,
    ExportExcel,
    AdminSecurity,
    Users,
    Roles,
    Telegram,
    Profile,
    ManagePermissions,
    ViewPermissions,
    ManageRoles,
    RestPassword,
    ActiveUser,
    DeactivateUser,
    Extension,
    ExportPdf,
    Folder,
    Translate,
    Email,
    Google,
    Microsoft,
    Info,
    CalendarMonth,
    PersonSearch,
    SettingsApplications,
    Facebook,
    Twitter,
    Apple,
    Logout,
    MicrosoftAzure,
    MicrosoftWindows,
    Key,
    Discord,
    Chat,
}